#pragma once

/*
 * FiveBarIK — forward/inverse kinematics for the symmetric parallel 5-bar
 * leg linkage, ported from MatLab_controls/wheeled_biped.m's fk()/ik()/
 * circInt()/jac() (closed-form, no iteration) — see telemetry_plan.md item D.
 *
 * Linkage (from wheeled_biped.m's fk() header comment):
 *   A = (-l5/2, 0)  rear hip pivot,  drives AB at angle phi1 from -x (i.e.
 *                   phi1=0 points BACKWARD, away from the body center --
 *                   "back hip negative X"), phi1 CW-positive
 *   E = (+l5/2, 0)  front hip pivot, drives ED at angle phi4 from +x
 *                   (phi4=0 points FORWARD, away from the body center --
 *                   "front hip positive X"), phi4 CCW-positive -- OPPOSITE
 *                   rotational sense from phi1 (confirmed 2026-09-02:
 *                   front CCW-positive, rear CW-positive -- swapped from
 *                   an earlier version of this file that had it backward,
 *                   front CW / rear CCW). Both zero references point
 *                   outward/away from the body centerline, matching a real
 *                   leg's natural "neutral" thigh direction and the real
 *                   hardware's mirror-mounted front/rear hip actuators.
 *                   This front/rear asymmetry is independent of, and not
 *                   to be confused with, the separate left/right HIP_SIGN
 *                   mirror correction CANMotor.cpp applies -- that one is
 *                   unaffected; this is baked into fk/ik/jac themselves,
 *                   exactly mirroring wheeled_biped.m.
 *   B = A - l1*(cos phi1, -sin phi1)         <- note the -sin, from phi1
 *                                                being CW-positive
 *   D = E + l4*(cos phi4, sin phi4)          <- plain +sin, from phi4
 *                                                being CCW-positive
 *   C = foot / wheel axle = circle(B,l2) ∩ circle(D,l3), lower branch
 *
 * SYMMETRY: with both zero references pointing outward, phi1=phi4=X is an
 * EXACT symmetric/straight-down pose (thL=0) for EVERY X, not a
 * coincidence at one value -- verified in wheeled_biped.m's selfcheck().
 *
 * L0 = virtual leg length = |OC| (O = midpoint of A,E).
 * thL = leg angle = atan2(x_C, -y_C), thL=0 straight down, thL>0 = foot
 * swung forward. Absolute (body-referenced) leg angle: theta = phi - thL
 * (phi = body pitch) — verified/corrected sign in wheeled_biped.m, NOT
 * theta = phi + thL.
 *
 * IMPORTANT: fk()/ik()'s internal (x,y) frame is the solver's own plain
 * Cartesian frame (y increasing UPWARD, matching wheeled_biped.m directly)
 * — NOT this firmware's NED (Z positive down) convention. Use
 * foot_point_ned() below to get NED-frame Cartesian foot-point position/
 * velocity for anything that needs to match StateIdx/RobotTelemetry's
 * sign convention; don't read fk()'s (x_C internal, y_C internal) directly
 * for that purpose.
 */

struct FiveBarParams {
    float l1, l2, l3, l4, l5;   // rear thigh, rear shin, front shin, front thigh, hip spacing [m]
};

struct FiveBarPose {
    float L0;    // virtual leg length [m]
    float thL;   // leg angle [rad], hip->foot, foot-forward positive
};

struct FiveBarVel {
    float L0_dot;    // leg extension rate [m/s]
    float thL_dot;   // leg angle rate [rad/s]
};

// J such that [L0_dot; thL_dot] = J * [phi1_dot; phi4_dot]. Row-major: m[row][col].
struct FiveBarJac {
    float m[2][2];
};

// Foot/wheel-axle point's position and velocity relative to the body,
// converted to NED convention (Z positive down) — see the header note above.
struct FootPointNed {
    float x, z;           // m, position relative to O (hip-pivot midpoint)
    float x_dot, z_dot;   // m/s
};

// Forward kinematics. Returns false (pose left unmodified) if phi1/phi4 put
// the linkage out of reach (the two circles don't intersect) — matches
// wheeled_biped.m's fk() throwing 'wheeled_biped:unreachable' for the same
// condition, just as a bool instead of an exception.
bool fk(const FiveBarParams& p, float phi1, float phi4, FiveBarPose& out);

// Closed-form inverse kinematics — no iteration, no initial guess. Returns
// false (phi1/phi4 left unmodified) if (L0, thL) isn't reachable.
bool ik(const FiveBarParams& p, float L0, float thL, float& phi1, float& phi4);

// Jacobian via central finite difference (wheeled_biped.m's jac() is an
// *exact* symbolic Jacobian generated by MATLAB's Symbolic Math Toolbox at
// derivation time — there's no static closed-form expression in the .m
// file to transcribe, only a generated function handle. A finite-difference
// C++ version is the explicitly-sanctioned fallback per telemetry_plan.md
// item D and controls_plan.md §3 — regression-test against wheeled_biped.m's
// own numbers before trusting it for anything control-facing).
FiveBarJac jac(const FiveBarParams& p, float phi1, float phi4);

// Convert joint angular rates to leg-space rates via the Jacobian.
FiveBarVel jac_to_vel(const FiveBarJac& J, float phi1_dot, float phi4_dot);

// pose/vel (in the leg-space L0/thL polar convention) -> NED-frame Cartesian
// foot-point position+velocity relative to the body. See telemetry_plan.md
// item D for the sign-flip derivation (z_NED = -y_internal, hence +cos not
// the internal frame's -cos) — flagged there as needing a bench check.
FootPointNed foot_point_ned(const FiveBarPose& pose, const FiveBarVel& vel);
